# -*- coding: utf-8 -*-
"""MCP_StockQuotes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147gzFdGMuApk4JqeB32qlyWSAwWP-Qih

# Setup
"""

!pip install openai langchain python-dotenv toml --quiet

import os
import re
import json
import requests

from openai import OpenAI

from google.colab import userdata
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
os.environ["ALPHAVANTAGE_API_KEY"] = userdata.get('ALPHAVANTAGE_API_KEY')
AI_MODEL = 'gpt-5-mini'

ALPHAVANTAGE_API_URL = "https://www.alphavantage.co/query"
ALPHAVANTAGE_API_KEY = os.environ["ALPHAVANTAGE_API_KEY"]

client=OpenAI(api_key=os.environ['OPENAI_API_KEY'])

"""# Direct API call

## Alphavantage
"""

def get_stock_quote(symbol: str) -> dict:
    """Fetch the latest stock quote for ``symbol`` using the Alpha Vantage API."""
    params = {"function": "GLOBAL_QUOTE", "symbol": symbol, "apikey": ALPHAVANTAGE_API_KEY}
    response = requests.get(ALPHAVANTAGE_API_URL, params=params, timeout=10)
    response.raise_for_status()
    data = response.json().get("Global Quote", {})
    if not data:
        return {"symbol": symbol.upper(), "price": None}
    return {
        "symbol": data.get("01. symbol", symbol.upper()),
        "price": float(data.get("05. price", "0") or 0.0),
        "change_percent": data.get("10. change percent"),
    }

"""## Yahoo Finance"""

!pip install yfinance --quiet
import yfinance as yf
import json

def get_stock_quote_yf(symbol: str) -> str:
    """Get current stock price and basic information."""
    try:
        stock = yf.Ticker(symbol)
        info = stock.info
        hist = stock.history(period="1d")
        if hist.empty:
            return json.dumps({"error": f"Could not retrieve data for {symbol}"})

        current_price = hist['Close'].iloc[-1]
        result = {
            "symbol": symbol,
            "current_price": round(current_price, 2),
            "company_name": info.get('longName', symbol),
            "market_cap": info.get('marketCap', 0),
            "pe_ratio": info.get('trailingPE', 'N/A'),
            "52_week_high": info.get('fiftyTwoWeekHigh', 0),
            "52_week_low": info.get('fiftyTwoWeekLow', 0)
        }
        return json.dumps(result, indent=2)

    except Exception as e:
        return json.dumps({"error": str(e)})

"""# Get quotes by calling API"""

get_stock_quote("TT")

get_stock_quote_yf("TT")

"""# GenAI without MCP"""

def get_completion(model, messages):
    print(f"\n\n*** Called get_completion on {messages}")
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        tools=[
            {
                "type": "function",
                "function": {
                    "name": "get_stock_quote",
                    "description": """Fetch the latest stock quote for ``symbol`` using the Alpha Vantage API.""",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "symbol": {
                                "type": "string",
                            },
                        },
                        "required": ["symbol"],
                    },
                },
            },
        ],
        temperature=1,
    )

    return response

import json

def answer_question(question, system_prompt="You are a helpful Financial Advisor."):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user",  "content": question},
    ]
    loop_count_limit = 5
    loop_count = 0

    while True:
        loop_count += 1
        if loop_count > loop_count_limit:
            raise Exception("Loop count exceeded")

        response = get_completion(AI_MODEL, messages)
        print(f"\n\n*** For input {messages}\n*** Received response {response}\n\n")

        choice = response.choices[0]
        msg = choice.message
        finish = choice.finish_reason

        # ---- Normal completion
        if finish == "stop":
            return msg.content

        # ---- Modern tools API (parallel tool calls)
        if finish == "tool_calls" and getattr(msg, "tool_calls", None):
            tool_calls = msg.tool_calls

            # Echo back assistant tool_calls (as dicts, not objects)
            messages.append({
                "role": "assistant",
                "content": None,
                "tool_calls": [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {
                            "name": tc.function.name,
                            "arguments": tc.function.arguments or "{}",
                        },
                    } for tc in tool_calls
                ]
            })

            # Execute each tool call and append the tool results
            for tc in tool_calls:
                fn_name = tc.function.name
                arg_json = tc.function.arguments or "{}"
                try:
                    args = json.loads(arg_json) if isinstance(arg_json, str) else (arg_json or {})
                except Exception:
                    args = {}

                # Prefer a single 'symbol' (case-insensitive); else pass kwargs
                if isinstance(args, dict):
                    symbol = args.get("symbol")
                    if symbol is None:
                        # try uppercase or other casings
                        for k in list(args.keys()):
                            if k.lower() == "symbol":
                                symbol = args[k]
                                break
                    if symbol is not None:
                        result = globals()[fn_name](symbol)
                    else:
                        result = globals()[fn_name](**args)
                else:
                    # args was not a dict → pass-through
                    result = globals()[fn_name](args)

                print(f"*** Called function {fn_name} with parameters {args}, returning {result}")

                messages.append({
                    "tool_call_id": tc.id,
                    "role": "tool",
                    "name": fn_name,
                    "content": json.dumps(result) if not isinstance(result, str) else result,
                })

            continue

        # ---- Legacy single function_call
        if finish == "function_call" and getattr(msg, "function_call", None):
            fn_name = msg.function_call.name
            arg_json = msg.function_call.arguments or "{}"
            try:
                args = json.loads(arg_json) if isinstance(arg_json, str) else (arg_json or {})
            except Exception:
                args = {}

            if isinstance(args, dict):
                symbol = args.get("symbol")
                if symbol is None:
                    for k in list(args.keys()):
                        if k.lower() == "symbol":
                            symbol = args[k]
                            break
                if symbol is not None:
                    result = globals()[fn_name](symbol)
                else:
                    result = globals()[fn_name](**args)
            else:
                result = globals()[fn_name](args)

            print(f"*** Called function {fn_name} with parameters {args}, returning {result}")

            # Echo assistant function_call (legacy)
            messages.append({
                "role": "assistant",
                "content": None,
                "function_call": {"name": fn_name, "arguments": arg_json},
            })
            # Then function result (legacy)
            messages.append({
                "role": "function",
                "name": fn_name,
                "content": json.dumps(result) if not isinstance(result, str) else result,
            })
            continue

        # Fallback: just return whatever text we got
        return msg.content or ""

q="How is Nvidia's stock today?"
a=answer_question(q,"You are a helpful Financial Planner.")
print(f"\n\nUser Question: {q}\nOpenAI Answer: {a}")

"""# GenAI with direct LLM-to-MCP connection"""

from openai import OpenAI

client = OpenAI()

response = client.responses.create(
    model="gpt-5-mini",
    input="Get the latest stock quote for AAPL using the Alpha Vantage MCP server. It is okay to get delayed or most recent close.",
    tools=[
        {
            "type": "mcp",
            "server_url": f"https://mcp.alphavantage.co/mcp?apikey={ALPHAVANTAGE_API_KEY}",
            "server_label": "alphavantage",
            "require_approval": "never"
        }
    ]
)

print(response.output_text)

"""# What does the MCP server call return?"""

import requests
from IPython.display import display, JSON, Markdown

url = f"https://mcp.alphavantage.co/mcp?apikey={ALPHAVANTAGE_API_KEY}"
payload = {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "tools/list"
}
response = requests.post(url, json=payload)
# print(response.json())

data = response.json()
# If it's a string, parse it
if isinstance(data, str):
    data = json.loads(data)


display(JSON(data))

import requests
import json
from IPython.display import display, Markdown

url = f"https://mcp.alphavantage.co/mcp?apikey={ALPHAVANTAGE_API_KEY}"
payload = {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "tools/list"
}

response = requests.post(url, json=payload)
data = response.json()

if isinstance(data, str):
    data = json.loads(data)

tools = data["result"]["tools"]

md = "## 📦 Alpha Vantage MCP Tools\n\n"

for tool in tools:
    md += f"### 🔧 `{tool['name']}`\n\n"
    md += f"{tool['description'].strip()}\n\n"
    props = tool["inputSchema"]["properties"]
    required = tool["inputSchema"].get("required", [])
    if props:
        md += "**Parameters:**\n"
        for k, v in props.items():
            req = " (required)" if k in required else ""
            md += f"- `{k}` ({v['type']}){req}: {v.get('description','')}\n"
        md += "\n"
    else:
        md += "_No parameters_\n\n"

display(Markdown(md))

import requests
import json
import ast
from IPython.display import display, JSON, Markdown

url = f"https://mcp.alphavantage.co/mcp?apikey={ALPHAVANTAGE_API_KEY}"

payload = {
    "jsonrpc": "2.0",
    "id": 2,
    "method": "tools/call",
    "params": {
        "name": "TOOL_GET",
        "arguments": {
            "tool_name": "GLOBAL_QUOTE"
        }
    }
}

resp = requests.post(url, json=payload)
#print(resp.status_code)
#print(resp.text)

outer = resp.json()
inner_text = outer["result"]["content"][0]["text"]
data = ast.literal_eval(inner_text)

md = f"""
### {data['name']}
{data['description'].strip()}
**Parameters**
"""
for k, v in data["parameters"]["properties"].items():
    req = " (required)" if k in data["parameters"]["required"] else ""
    md += f"- **{k}** ({v['type']}){req}: {v['description']}\n"
display(Markdown(md))